#!/bin/bash
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:01:59
#SBATCH --output=mpi_fft.out
#SBATCH -A anakano_429

module purge
module load usc
module load python 

INPUT_FILE=input20.in
counter=0
while [ $counter -lt 3 ]; do
  echo "***** Serial FFT *****"
  mpirun -n 1 python3 mpi_fft.py $INPUT_FILE
  echo "***** Parallel FFT with $SLURM_NTASKS ranks *****"
  mpirun -n $SLURM_NTASKS python3 mpi_fft.py $INPUT_FILE
  let counter+=1
done